name: PR coverage / report

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Tox
      run: pip install tox

    - name: Run test
      run: tox -e test
    
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        junitxml-path: ./pytest.xml
        pytest-xml-coverage-path: ./cov.xml
