name: PR coverage / report

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run test
      run: |
        uv run --group test pytest \
          -vv \
          --timeout=120 \
          --junitxml=pytest.xml \
          --cov-config=pyproject.toml \
          --cov=src \
          --cov-report html:cov_html \
          --cov-report xml:cov.xml \
          --cov-fail-under=97

    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        junitxml-path: ./pytest.xml
        pytest-xml-coverage-path: ./cov.xml
